name: Firmware CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sms-otp-firmware

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Firmware
        run: pio run
