name: Vue Docs CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        working-directory: ./documentations
        with: |
          node-version: '20.8.0'

      - name: Installing documentation modules and dependencies
        run: npm install
        
      - name: Building documentation pages
        run: npm run build-only
